export const SET_CUSTOMER_ID = "SET_CUSTOMER_ID";
export const SET_MANAGER_ID = "SET_MANAGER_ID";
export const SET_MANAGER = "SET_MANAGER";
export const SET_EMPLOYEE_ID = "SET_EMPLOYEE_ID";
export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const SET_CUSTOMER = "SET_CUSTOMER";
export const SET_POOL_SESSIONS = "SET_POOL_SESSIONS";
export const SET_STUDIO_SESSIONS = "SET_STUDIO_SESSIONS";
export const SET_CLIMBING_SESSIONS = "SET_CLIMBING_SESSIONS";
export const SET_SQUASH_COURT_1_SESSIONS = "SET_SQUASH_COURT_1_SESSIONS";
export const SET_SQUASH_COURT_2_SESSIONS = "SET_SQUASH_COURT_2_SESSIONS";
export const SET_FITNESS_ROOM_SESSIONS = "SET_FITNESS_ROOM_SESSIONS";
export const SET_SPORTS_HALL_SESSIONS = "SET_SPORTS_HALL_SESSIONS";
export const SET_CAPACITIES = "SET_CAPACITIES";
export const SET_BOOKED_SESSIONS = "SET_BOOKED_SESSIONS";
export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const SET_POOL = "SET_POOL";
export const SET_STUDIO = "SET_STUDIO";
export const SET_FITNESS_ROOM = "SET_FITNESS_ROOM";
export const SET_SPORTS_HALL = "SET_SPORTS_HALL";
export const SET_SQUASH_COURT_1 = "SET_SQUASH_COURT_1";
export const SET_SQUASH_COURT_2 = "SET_SQUASH_COURT_2";
export const SET_CLIMBING_WALL = "SET_CLIMBING_WALL";
export const POOL = "swimming-pool";
export const STUDIO = "studio";
export const FITNESS_ROOM = "fitness-room";
export const SPORTS_HALL = "sports-hall";
export const SQUASH_COURT_1 = "squash-court1";
export const SQUASH_COURT_2 = "squash-court2";
export const CLIMBING_WALL = "climbing-wall";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const TOGGLE_LOADING = "SET_LOADING";
export const TOGGLE_LOADING_FORM = "TOGGLE_LOADING_FORM";
export const SET_CART = "SET_CART";
export const SET_INFO = "SET_INFO";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const TOGGLE_OVERLAY = "TOGGLE_OVERLAY";
export const TOGGLE_BASKET = "TOGGLE_BASKET";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const TOGGLE_BOOK_FORM = "TOGGLE_BOOK_FORM";
export const SET_IS_BOOK = "SET_IS_BOOK";
export const SET_BOOKED_TIME = "SET_BOOKED_TIME";
export const SET_ALL_FACILITIES = "SET_ALL_FACILITIES";

export const SET_BOOKED_SESSIONS_STATS = "SET_BOOKED_SESSIONS_STATS";
export const SET_FACILITY_ACTIVITY_STATS = "SET_FACILITY_ACTIVITY_STATS";
export const SET_TOTAL_PROFIT = "SET_TOTAL_PROFIT";
export const SET_TOTAL_PROFIT_FACILITY = "SET_TOTAL_PROFIT_FACILITY";
export const SET_TOTAL_PROFIT_ACTIVITY = "SET_TOTAL_PROFIT_ACTIVITY";
export const SET_TOTAL_PROFIT_PER_FACILITY_PER_ACTIVITY =
  "SET_TOTAL_PROFIT_PER_FACILITY_PER_ACTIVITY";

export const TOTAL_NUMBER_OF_CUSTOMER = "TOTAL_NUMBER_OF_CUSTOMER";
export const TOTAL_NUMBER_OF_MEMBERS = "TOTAL_NUMBER_OF_MEMBERS";
export const TOTAL_NUMBER_OF_NON_MEMBERS = "TOTAL_NUMBER_OF_NON_MEMBERS";
export const SET_TOTAL_PROFIT_All_FACILITIES =
  "SET_TOTAL_PROFIT_All_FACILITIES";

export const SET_TOTAL_PROFIT_All_ACTIVITIES =
  "SET_TOTAL_PROFIT_All_ACTIVITIES";
